POST http://localhost:8000/api/auth/refresh
Content-Type: application/json

{
    "username": "Jim"
}

###

GET http://localhost:8000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjU3LCJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNzc2MjY1Mjk0LCJleHAiOjE3NzYyNjg4OTR9.SsoJdou_byI3YD_FUPtt3KrfuEVMaMkwkMW4t9P-W0c
### 

POST http://localhost:8000/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "test1234",
    "type": "Sign-Up"
}
### Refresh
POST http://localhost:5000/refresh

### Logout
GET http://localhost:5000/logout    
```

###
### Me
GET http://localhost:8000/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjU3LCJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNzc0NTMwMTc2LCJleHAiOjE3NzQ1MzM3NzZ9.hMWgUp7vfEjYxQYqgW4zfttZnyi_8KX_VRX6ObchnmM